# Generated by Django 2.2.1 on 2019-05-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_remove_nota_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='slug',
            field=models.SlugField(default='#', max_length=225),
        ),
        migrations.AddField(
            model_name='periodista',
            name='slug',
            field=models.SlugField(default='#', max_length=225),
        ),
    ]
